name: Test Python Input

on: [push]

jobs:
  run-python-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      
      - name: Execute Test Script
        run: |
          python3 main.py
        env:
          INPUT: "hello world"